### ISSUE TITLE
certificate issue

### ISSUE THREAD

**Issue by gmanchon** [lewagon/recipes#3]
Looks like the SSL certificate for https://recipes.lewagon.com/ has expired

```
SSLError: HTTPSConnectionPool(host='recipes.lewagon.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1131)')))
```

@ssaunier other candidates for expired certificates :
- ❌ https://iex.lewagon.com/
- ✅ https://opengraph.lewagon.com/ [handled](https://github.com/lewagon/opengraph/issues/4)

No other urls found.

**Comment by ssaunier** [comment]
Fixed ✅

**Comment by gmanchon** [comment]
Thanks ! 🙏
